logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: ${PORTA_PADRAO:8090}
  error:
    include-message: always
  servlet:
    context-path: ${CONTEXT_PATH:/agenda}

spring:
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/agenda}
    username: ${USERNAME_DB:agenda}
    password: ${PASSWORD_DB:agenda}
  messages:
    basename: i18n/messages

  jpa:
    hibernate:
      ddl-auto: validate

link-images:
  padrao:
    cidade: ${LINK_PADRAO_CIDADES:https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGNpdHl8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60}
    evento: ${LINK_PADRAO_EVENTOS:https://images.unsplash.com/photo-1561912774-79769a0a0a7a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGV2ZW50c3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60}
    local: ${LINK_PADRAO_LOCAIS:https://images.unsplash.com/photo-1544997872-62aabbe63823?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvY2FsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60}
    pessoa: ${LINK_PADRAO_PESSOA:https://images.unsplash.com/photo-1510723185481-c39848b105c0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGFub255bW91c3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60}